### ISSUE TITLE
is this add-on still maintained and updated?

### ISSUE THREAD

**Issue by MadMirza** [tonyldo/tonyldo-hassio-addons#14]
hi,
Just wanted to know if the addon is still under development or any kind of support, it would be great if that's the case.
Also, This addon is an impressive work, TTlocks are picking popularity and there would be plenty of people who would appreciate and support you with this work. 
Once Again, This addon has be so so useful for me, thanks for this, I would love to support you in other ways possible!!

**Comment by tonyldo** [comment]
At moment i m only fixing bugs. I m happy to read yours worlds and hopping for any help.

**Comment by tonyldo** [comment]
closing...
