### ISSUE TITLE
token changed

### ISSUE THREAD

**Issue by goldbe4804** [tonyldo/tonyldo-hassio-addons#18]
my lock has been working great for about 2 mos not iam getting this error i think i have to update the token?? -- how do i do that?
2022-08-14 10:04:27 - [ERROR] TTLOCK2MQTT: Error main method
Traceback (most recent call last):
  File "/usr/bin/ttlock_adapter.py", line 326, in main
    createClients(broker, port, broker_user, broker_pass,
  File "/usr/bin/ttlock_adapter.py", line 306, in createClients
    for gateway in ttlock.get_gateway_generator():
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 99, in get_gateway_generator
    _response = TTLock.__send_request__(_url_request).json()
  File "/usr/local/lib/python3.10/site-packages/ttlockwrapper/ttlock.py", line 28, in __send_request__
    raise TTlockAPIError(error_code=_response.json().get(ERROR_CODE_FIELD),menssage=_response.json().get(MENSSAGE_FIELD))
ttlockwrapper.ttlock.TTlockAPIError: Error returned from TTlockAPI: Error_code 10004 - invalid grant

thanks for any help

**Comment by maxrd** [comment]
me too .help

**Comment by tonyldo** [comment]
on a unix system....

```
sudo apt install python3
python3 -m pip install ttlockio
```

if u have the refresh token: 
`refresh_access_token clientId clientSecret refreshToken someRedirectUrl`

if u dont keep the refresh token:
```
python

>>> import ttlockwrapper
>>> result_user=ttlockwrapper.TTLock.create_user('****************************','****************************','tester1','123456abcde').get('username')
>>> print(result_user)
homeassistant_tester1
>>> token=ttlockwrapper.TTLock.get_token('****************************','****************************','homeassistant_tester1','123456abcde','https://****************************.duckdns.org/')
>>> print(token)
{'access_token': '****************************', 'uid': 12007440, 'refresh_token': '****************************', 'openid': 1627987697, 'scope': 'user,key,room', 'token_type': 'Bearer', 'expires_in': 7776000}

```

**Comment by goldbe4804** [comment]
ty for your responce
i have :

"ttlockclientapp": "c120????03b4???????20b695",
    "ttlocktoken": "84f??????????ff276?l,joie20",
    "username": "bigc??????????",
    "refreshtoken": "edfe24a31????Ss;eflpwfp[k??????b"

i seem to have the refreshtoken (see above) so i can enter:

edfe24a31????Ss;eflpwfp[k??????b clientId clientSecret refreshToken someRedirectUrl

and that would be it?
iam working with a pi4 and would be unsing SSH & Web Terminal
thanks jeff

**Comment by tonyldo** [comment]
if u have the refresh token u will execute the commands (in a unix like system):
```
sudo apt install python3
python3 -m pip install ttlockio
refresh_access_token c120????03b4???????20b695 YOURTTLOCKAPISECRETHERE edfe24a31????Ss;eflpwfp[k??????b https://your.url.hass.for.example
```

**Comment by goldbe4804** [comment]
thank you !!!!!

**Comment by goldbe4804** [comment]
sorry still can use some help
i run python3 -m pip install ttlockio 
and get whats on my screen shot (and also says requirement already satisfied
then run 
refresh_access_token  ......................
and get command not found see screen shot
thanks for any help
and sorry new to this command line stuff 
![ttlock](https://user-images.githubusercontent.com/56876314/189963168-d54f8924-e1be-49f3-82ce-81d519379eb8.JPG)

**Comment by tonyldo** [comment]
please try the new version tutorial at https://github.com/tonyldo/ttlockio

**Comment by goldbe4804** [comment]
Thank you for your help -- it wasnt ez (for me) but my lock is refreshed and up and running ~~!!!
it worked with 
refresh_access_token clientid clientsecret refreshtoken
