### ISSUE TITLE
TTLock API url changing

### ISSUE THREAD

**Issue by haggis663** [tonyldo/tonyldo-hassio-addons#19]
The URL to the api on ttlock is changing.
Original domain name: [api.ttlock.com](http://api.ttlock.com/)
New domain name (China): [cnapi.ttlock.com](http://cnapi.ttlock.com/)
New domain name (Out of China): [euapi.ttlock.com](http://euapi.ttlock.com/)

Original domain name: [api.sciener.com](http://api.sciener.com/)
New domain name (China): [cnapi.sciener.com](http://cnapi.sciener.com/)
New domain name (Out of China): [euapi.sciener.com](http://euapi.sciener.com/)

**Comment by tonyldo** [comment]
working on it...
