### ISSUE TITLE
Unable to get account password

### ISSUE THREAD

**Issue by javierel** [tonyldo/tonyldo-hassio-addons#23]
I know this is not related to the addon itself (yet) but have been unable to get user/password for the App, I registered in ttlock site and got approval for the App, received client_id and client_secret wich I included in the HTTP request (POST) along with the other parameters but although the answer I get is: 200 OK, the JSON text in the result says: 
{
"errcode": 10007,
"errmsg": "invalid account or invalid password",
"description": "username或password错误"
}
Any help is appreciated.

**Comment by tonyldo** [comment]
Have you followed the steps in ttlockio repository? Step 4!

**Comment by javierel** [comment]
First of all thanks for your quick response...
Yes it worked following step 4, I usually search and read before asking for help, this time I did tried that (#4) but got an error (dont remember what) and then tried a lot of other ways and pages without success.
TTLock2MQTT Addon in Home Asistant is now running, log only shows:
2023-04-04 16:56:56 - [INFO] TTLOCK2MQTT: Current threads: 1, so I presume no errors but how can I relate this Addon to my Mosquitto broker? I don't see any way to configure the broker address, username/password. Is there something I'm missing?

**Comment by tonyldo** [comment]
About mqtt, Ttlock2mqtt uses your mqtt addon, you don't need to put then in ttlock2mqtt config. 
https://developers.home-assistant.io/docs/add-ons/communication/#services-api

And the fact that there is no more threads, it is look like the addon didnt find any ttlock device.
Do you add your ttlock device on the new user created at step 4?
