### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Sthopeless** [tonyldo/tonyldo-hassio-addons#5]
Is it possible to add:

* On the auto-discovery add `Manufacturer` maybe TTLock or TTLock2MQTT (I prefer last one best) and also a `Model` maybe import `modelNum` [from the API](https://open.ttlock.com/doc/api/v3/lock/detail)

* freeze and unfreeze option and status 
* a toggle button to update the gateway and the door lock
* Create a sensor that displays unlock records
* Allow to change auto lock time
  > maybe a `input_number` where the entered value would be the seconds it takes to unlock with a default of 10/30secs

Present this addon in Home Assistant forum, surely others will appreciate this. Also maybe because the process is somewhat complicated create something like a Discord channel where 'we' can offer help without information being spread all around and have to repeat and reply constantly to the same questions on multiple posts.

It looks very good thank you and sorry for all the questions!!!

**Comment by tonyldo** [comment]
I am going work on this now, and the "sending records from lock to hass as a event trigger" feature
