### ISSUE TITLE
Significant delay to action request and between reporting of locked and unlocked 

### ISSUE THREAD

**Issue by botts7** [tonyldo/tonyldo-hassio-addons#7]
Thank you for this awesome add on!

My lock takes around 10 seconds to unlock or lock after I trigger it in home assistant.

also

My lock is set to auto lock after 10 seconds of triggering the opening. 

Home Assistant does not report the lock is "locked" for around 60 seconds. Is there a way to publish the change to the broker more quickly or take this auto lock function into consideration?

**Comment by Sthopeless** [comment]
i don't think the opening delay can be reduced or altered for that matter, when you request the door lock to open the gateway still needs to look for the lock which is most of the time 'sleeping'. 
If you try to touch the keypad or awake the door before sending unlock you may notice it happens almost instantly

**Comment by tonyldo** [comment]
Anyway it is good idea have separated delays for battery and state. And make these settings available for the add-on configuration.

**Comment by tonyldo** [comment]
version 0.2 avaible.
Two new options with these default values:
publishbatterydelay: 300
publishstatedelay: 60
