### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Elder-HVAC-Man** [tonyldo/tonyldo-hassio-addons#8]
Get the following error when trying to install:

20-10-05 21:03:44 INFO (SyncWorker_0) [supervisor.docker.addon] Start build aab028cf/armv7-addon-ttlock2mqtt:0.2
20-10-05 21:03:47 ERROR (SyncWorker_0) [supervisor.docker.addon] Can't build aab028cf/armv7-addon-ttlock2mqtt:0.2: The command '/bin/ash -o pipefail -c pip3 install -r /tmp/requirements.txt' returned a non-zero code: 127

Any suggestions?

Thanks

**Comment by tonyldo** [comment]
Sorry to answer so late... which is your hassio enviroment (OS, how did u intall hassio...)??

**Comment by Elder-HVAC-Man** [comment]
HassOS 4.13, Raspberry Pi 4B, originally installed from the HassOS image.  Not sure what other info you need.  Thank you for looking into this.

**Comment by Elder-HVAC-Man** [comment]
Sorry to bother you, but do you have any suggestions on how to get this working?  I would love to integrate my lock into HA.

**Comment by tonyldo** [comment]
I know what happened with u... I am using pre build images for python addons:
(https://github.com/tonyldo/tonyldo-hassio-addons/blob/a6b803f75c3435067726e5e907915d31a44b41b5/ttlock2mqtt/build.json#L2-L6)
And i see that there is no image for rasp pi 4 architecture!
https://github.com/home-assistant/docker-base#python-images
I m figure out how to solve this... but for now my addon has no support for rasp pi 4 hass enviorement

**Comment by Elder-HVAC-Man** [comment]
Thank you for checking.  I will wait until you include support for rasp pi 4 hass environment.

**Comment by DanPatten** [comment]
I am running into this same issue, can you please add support for raspberry pi 4?

@tonyldo looks like they support this now: https://github.com/home-assistant/docker-base#raspbian-images
